### ISSUE TITLE
Items are pulling random metadata from other records, reindexing doesn't fix

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pomegranate#536] opened 2019-02-28 17:17 UTC
Record: https://dpul.princeton.edu/eastasian/catalog/xg94hs896

**Comment by tventimi** [comment] 2019-04-23 12:10
[dpul_subject_mismatches.xlsx](https://github.com/pulibrary/pomegranate/files/3107382/dpul_subject_mismatches.xlsx)

Attached is a file of examples of this problem.  The tab "eastasian" contains 92 examples from the DPUL site https://dpul.princeton.edu/eastasian with the (incorrect) subjects 

Medicine, Chinese—Early works to 1800
Medicine, Chinese—Formulae, receipts, prescriptions

The tab "ealtoc" contains 36 examples from https://dpul.princeton.edu/ealtoc with the incorrect subjects

Chinese poetry—19th century
Chinese poetry—20th century
Chinese poetry—Societies, etc—History—Sources

**Comment by tventimi** [comment] 2019-05-13 12:58
A staff member has reported what appears to be a related problem.  Please note that more than just subjects are involved now.

All nine Korean records still pull up the wrong information in edition, abstracts, contents, editors, etc.

https://dpul.princeton.edu/ealtoc/catalog?f%5Breadonly_language_ssim%5D%5B%5D=Korean&q=

**Comment by hackmastera** [comment] 2019-05-14 18:42
This looks like the chinese record those korean records are pulling data from
https://figgy.princeton.edu/catalog/b1e79dcc-9ff5-4786-9bc5-f863291defcf

**Comment by hackmastera** [comment] 2019-05-14 18:46
Here's a pair:
https://dpul.princeton.edu/msstreasures/catalog/zc77sr50z "the book of enoch"
has metadata from https://figgy.princeton.edu/catalog/87c05bba-8946-4773-bace-5630ef141c7f "Dettingen Te Deum"

**Comment by hackmastera** [comment] 2019-05-14 19:14
@jrgriffiniii and I looked at some of these examples and tried to identify any common factors between "source" and "corrupted" records. We looked at last modified dates and did not find a pattern (in one case the "source" had an earlier modified date and in the other case it had a later modified date).

We note that the problem is definitely at the pomegranate layer; the corrupted records look right in figgy.

Note also that one source record will provide data to many (sometimes very many) corrupted records. It looks like the source and corrupted records are members of the same collection.

In the case of the Handel "source" record, it seems to be corrupting maybe the entire "Treasures of the Manuscripts" collection. Is it possible that the Handel record is being used to supply exhibit-level metadata? I checked its create / update dates against other members of that collection and it's not the first or last of either.

**Comment by tpendragon** [comment] 2019-05-14 22:18
https://github.com/pulibrary/pomegranate/pull/586 will potentially fix this after it's deployed and some objects are reindexed.

**Comment by tventimi** [comment] 2019-06-04 13:30
This issue has been fixed, at least in the East Asian examples I initially reported.

**Comment by escowles** [comment] 2019-06-12 18:13
Fixed by #586 

Thanks for confirming @tventimi !

**Closed by escowles** 2019-06-12 18:13 UTC
Labels: bug, high-priority
