### ISSUE TITLE
Default fields on new collection creation

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pomegranate#442] opened 2018-11-26 19:01 UTC
@joycebcat I'm creating this because I know you've talked about it before. Has there been a decision on which fields to have by default?

**Comment by joycebcat** [comment] 2018-11-27 15:43
@tpendragon It is more a question of what NOT to display by default.  I don't know if you can do this because the fields are conditional on what is present in the originating records, but here is a list of fields NOT to display and the reason why.  These are also in a doc in the team drive.

Title (already included as the header)
Published/Created (covered by publisher)
Range label
Creator (not both creator and author)
Title sort
Created
Date (covered by publisher)
Type (covered by subject)
Location (covered by call number)
Spatial (covered by subject)

**Comment by hackmastera** [comment] 2019-09-27 13:58
duplicate of #246. The superset of fields to not display is:

Title (already included as the header)
Published/Created (covered by publisher)
Range label
Creator (not both creator and author)
Title sort
Created
Date (covered by publisher)
Type (covered by subject)
Location (covered by call number)
Spatial (covered by subject)
collection
references

**Comment by hackmastera** [comment] 2019-09-27 16:17
so when a spotlight exhibit is created, a `Spotlight::BlacklightConfiguration` is created and saved. That object holds `index_fields` which I think are what we want to set these defaults on. check for each field in the blacklist and if found set it to `"show"=>false`.

**Comment by hackmastera** [comment] 2019-09-27 17:33
`Spotlight::BlacklightConfigurationDefaults` is initializing default settings for search fields and sort fields, but not for index fields. Write something into there?

The first time an exhibit is created `index_fields` is blank. It's not populated with actual field configurations until the first save in the UI. So what if we populate those check boxes when `index_fields` is blank? Trace down the source of config logic in`metadata_field` template.

**Comment by hackmastera** [comment] 2019-10-01 15:37
The index fields are initially populated from custom fields linked to the exhibit. The blacklight configuration would filter them out if we set `if` to `false` in their `configuration` attribute. But I'm not really sure where these are created.

**Comment by hackmastera** [comment] 2020-01-27 20:02
duplicate of #246

**Closed by hackmastera** 2020-01-27 20:02 UTC
Labels: enhancement
