### ISSUE TITLE
StartCanvas in SimpleResource JSON-LD causing Solr errors.

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pomegranate#1208] opened 2021-11-03 17:17 UTC
The exhibit indexes without exceptions, but a single resource does not index. 

https://figgy.princeton.edu/catalog/3fe9a53f-4d11-4ed0-bb29-086a9b9ebc08
https://dpul.princeton.edu/pudl0036
Exhibit id: 112

See https://github.com/pulibrary/figgy/issues/4777

**Comment by eliotjordan** [comment] 2021-11-03 18:45
Started re-index of Exhibit.

**Comment by eliotjordan** [comment] 2021-11-08 18:36
It didn't reindex. No errors as far as I can tell.

**Comment by tpendragon** [comment] 2021-11-08 18:42
https://figgy.princeton.edu/concern/scanned_resources/3fe9a53f-4d11-4ed0-bb29-086a9b9ebc08/manifest The viewingHint is marked as multi-part for some reason, I wonder if that's causing it? It's not a MVW.

**Comment by hackartisan** [comment] 2021-11-08 18:50
This one has that multi-part viewing hint, too, and it indexed fine. https://figgy.princeton.edu/concern/scanned_resources/a53b19fe-04a2-4ed1-a163-1acd8bcff1bb/manifest

**Comment by tpendragon** [comment] 2021-11-08 18:59
When I reindex from the console I get an error from this solr document:

```json
[
    {
        "spotlight_resource_id_ssim": "gid://pomegranate/IIIFResource/155513",
        "spotlight_resource_type_ssim": "iiif_resources",
        "id": "c0975b9a063a4b044f1f6cee28627979",
        "exhibit_pudl0036_public_bsi": true,
        "exhibit_pudl0036_override-title_ssim": null,
        "override-title_tesim": null,
        "exhibit_pudl0036_readonly_identifier_ssim": [
            "ark:/88435/bv73c422q"
        ],
        "readonly_identifier_tesim": [
            "ark:/88435/bv73c422q"
        ],
        "exhibit_pudl0036_readonly_edm-rights_ssim": [
            "In Copyright - Educational Use Permitted"
        ],
        "readonly_edm-rights_tesim": [
            "In Copyright - Educational Use Permitted"
        ],
        "exhibit_pudl0036_readonly_collections_ssim": [
            "Interborough Rapid Transit Company Subway Posters"
        ],
        "readonly_collections_tesim": [
            "Interborough Rapid Transit Company Subway Posters"
        ],
        "exhibit_pudl0036_readonly_start-canvas_ssim": [
            {
                "id": "c2edaf24-c854-4a9c-ae11-7f9b6de970a1"
            }
        ],
        "readonly_start-canvas_tesim": [
            {
                "id": "c2edaf24-c854-4a9c-ae11-7f9b6de970a1"
            }
        ],
        "exhibit_pudl0036_readonly_viewing-hint_ssim": [
            "individuals"
        ],
        "readonly_viewing-hint_tesim": [
            "individuals"
        ],
        "exhibit_pudl0036_readonly_visibility_ssim": [
            "open"
        ],
        "readonly_visibility_tesim": [
            "open"
        ],
        "exhibit_pudl0036_readonly_abstract_ssim": [
            "Advertising poster for the Interborough Rapid Transit Company of New York City, providing instructions on how to pay the fare for two people using the new fare gates. Includes image of two men using the fare gate"
        ],
        "readonly_abstract_tesim": [
            "Advertising poster for the Interborough Rapid Transit Company of New York City, providing instructions on how to pay the fare for two people using the new fare gates. Includes image of two men using the fare gate"
        ],
        "exhibit_pudl0036_readonly_extent_ssim": [
            "1 poster; approximately 21\u00d716 inches"
        ],
        "readonly_extent_tesim": [
            "1 poster; approximately 21\u00d716 inches"
        ],
        "exhibit_pudl0036_readonly_genre_ssim": [
            "posters"
        ],
        "readonly_genre_tesim": [
            "posters"
        ],
        "exhibit_pudl0036_readonly_part-of_ssim": [
            "http://arks.princeton.edu/ark:/88435/m039k489x"
        ],
        "readonly_part-of_tesim": [
            "http://arks.princeton.edu/ark:/88435/m039k489x"
        ],
        "exhibit_pudl0036_readonly_replaces_ssim": [
            "http://pudl.princeton.edu/objects/52e84d81-5abc-4f0c-9b25-97d21c5c94e4"
        ],
        "readonly_replaces_tesim": [
            "http://pudl.princeton.edu/objects/52e84d81-5abc-4f0c-9b25-97d21c5c94e4"
        ],
        "exhibit_pudl0036_readonly_title_ssim": [
            "To Pay Another's Fare"
        ],
        "readonly_title_tesim": [
            "To Pay Another's Fare"
        ],
        "exhibit_pudl0036_readonly_creator_ssim": [
            "Interborough Rapid Transit Company"
        ],
        "readonly_creator_tesim": [
            "Interborough Rapid Transit Company"
        ],
        "exhibit_pudl0036_readonly_date_ssim": [
            "1922-02"
        ],
        "readonly_date_tesim": [
            "1922-02"
        ],
        "exhibit_pudl0036_readonly_language_ssim": [
            "English"
        ],
        "readonly_language_tesim": [
            "English"
        ],
        "exhibit_pudl0036_readonly_subject_ssim": [
            "Advertising",
            "Subways",
            "New York (N.Y.)",
            "Posters",
            "Lee, Ivy L. (Ivy Ledbetter), 1877-1934"
        ],
        "readonly_subject_tesim": [
            "Advertising",
            "Subways",
            "New York (N.Y.)",
            "Posters",
            "Lee, Ivy L. (Ivy Ledbetter), 1877-1934"
        ],
        "exhibit_pudl0036_readonly_rights-statement_ssim": [
            "http://rightsstatements.org/vocab/InC-EDU/1.0/"
        ],
        "readonly_rights-statement_tesim": [
            "http://rightsstatements.org/vocab/InC-EDU/1.0/"
        ],
        "exhibit_pudl0036_readonly_holding-location_ssim": [
            "https://bibdata.princeton.edu/locations/delivery_locations/9"
        ],
        "readonly_holding-location_tesim": [
            "https://bibdata.princeton.edu/locations/delivery_locations/9"
        ],
        "exhibit_pudl0036_readonly_location_ssim": [
            "MC085. Box 136"
        ],
        "readonly_location_tesim": [
            "MC085. Box 136"
        ],
        "exhibit_pudl0036_readonly_downloadable_ssim": [
            "public"
        ],
        "readonly_downloadable_tesim": [
            "public"
        ],
        "exhibit_pudl0036_readonly_range-label_ssim": [
            "Main Structure"
        ],
        "readonly_range-label_tesim": [
            "Main Structure"
        ],
        "spotlight_exhibit_slug_pudl0036_bsi": true,
        "exhibit_pudl0036_tags_ssim": null,
        "spotlight_exhibit_slugs_ssim": [
            "pudl0036"
        ],
        "access_identifier_ssim": [
            "bv73c422q"
        ],
        "override-title_ssim": null,
        "readonly_identifier_ssim": [
            "ark:/88435/bv73c422q"
        ],
        "readonly_edm-rights_ssim": [
            "In Copyright - Educational Use Permitted"
        ],
        "readonly_collections_ssim": [
            "Interborough Rapid Transit Company Subway Posters"
        ],
        "readonly_start-canvas_ssim": [
            {
                "id": "c2edaf24-c854-4a9c-ae11-7f9b6de970a1"
            }
        ],
        "readonly_viewing-hint_ssim": [
            "individuals"
        ],
        "readonly_visibility_ssim": [
            "open"
        ],
        "readonly_abstract_ssim": [
            "Advertising poster for the Interborough Rapid Transit Company of New York City, providing instructions on how to pay the fare for two people using the new fare gates. Includes image of two men using the fare gate"
        ],
        "readonly_extent_ssim": [
            "1 poster; approximately 21\u00d716 inches"
        ],
        "readonly_genre_ssim": [
            "posters"
        ],
        "readonly_part-of_ssim": [
            "http://arks.princeton.edu/ark:/88435/m039k489x"
        ],
        "readonly_replaces_ssim": [
            "http://pudl.princeton.edu/objects/52e84d81-5abc-4f0c-9b25-97d21c5c94e4"
        ],
        "readonly_title_ssim": [
            "To Pay Another's Fare"
        ],
        "readonly_creator_ssim": [
            "Interborough Rapid Transit Company"
        ],
        "readonly_date_ssim": [
            "1922-02"
        ],
        "readonly_language_ssim": [
            "English"
        ],
        "readonly_subject_ssim": [
            "Advertising",
            "Subways",
            "New York (N.Y.)",
            "Posters",
            "Lee, Ivy L. (Ivy Ledbetter), 1877-1934"
        ],
        "readonly_rights-statement_ssim": [
            "http://rightsstatements.org/vocab/InC-EDU/1.0/"
        ],
        "readonly_holding-location_ssim": [
            "https://bibdata.princeton.edu/locations/delivery_locations/9"
        ],
        "readonly_location_ssim": [
            "MC085. Box 136"
        ],
        "readonly_downloadable_ssim": [
            "public"
        ],
        "readonly_range-label_ssim": [
            "Main Structure"
        ],
        "sort_title_ssi": "To Pay Another's Fare",
        "sort_date_ssi": "1922-02",
        "sort_author_ssi": null,
        "system_created_at_dtsi": "2018-09-04T21:42:07Z",
        "system_updated_at_dtsi": "2021-07-14T16:04:32Z",
        "full_title_tesim": [
            "To Pay Another's Fare"
        ],
        "thumbnail_ssim": "https://iiif-cloud.princeton.edu/iiif/2/95%2Fb9%2F4e%2F95b94e40f2814cfe9f2b78894307e3da%2Fintermediate_file/full/!200,150/0/default.jpg",
        "full_image_url_ssm": "https://iiif-cloud.princeton.edu/iiif/2/95%2Fb9%2F4e%2F95b94e40f2814cfe9f2b78894307e3da%2Fintermediate_file/full/!600,600/0/default.jpg",
        "content_metadata_iiif_manifest_field_ssi": "https://figgy.princeton.edu/concern/scanned_resources/3fe9a53f-4d11-4ed0-bb29-086a9b9ebc08/manifest",
        "tile_source_ssim": [
            "https://iiif-cloud.princeton.edu/iiif/2/95%2Fb9%2F4e%2F95b94e40f2814cfe9f2b78894307e3da%2Fintermediate_file/info.json"
        ]
    }
]

```

I think the problem is it's indexing start canvas with an ID.

**Comment by hackartisan** [comment] 2021-11-10 15:03
I deployed the figgy fix and started another reindex of this collection.

**Closed as completed** 2021-11-10 16:31 UTC
