### ISSUE TITLE
Changing banner image

### ISSUE THREAD

**Issue by kelea99** [pulibrary/pomegranate#478] opened 2018-12-27 16:24 UTC
A thought about the banner image. Perhaps changing image to a selection of a marbled endpaper from one of the digitized rare books would work well (especially behind the "DPUL" text overlaying it). 

rough idea (I just chose an endpaper at random as an example):
![dpul_design_idea_01](https://user-images.githubusercontent.com/45043014/50494924-1f1a5380-09f4-11e9-8fa6-51683fc68b05.png)

**Comment by tpendragon** [comment] 2019-09-19 15:56
Closed as duplicate of #410

**Closed by tpendragon** 2019-09-19 15:56 UTC
Labels: enhancement, question
