### ISSUE TITLE
Hide or improve rendering of References

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pomegranate#446] opened 2018-11-26 21:52 UTC
This isn't great UI. https://dpul.princeton.edu/eastasian/catalog/kd17cx20w

<img width="790" alt="screenshot 2018-11-26 15 51 51" src="https://user-images.githubusercontent.com/784196/49044428-5ac2c300-f193-11e8-8f91-b10daa69939e.png">

**Comment by escowles** [comment] 2018-11-28 19:51
I'm having trouble reproducing this — when I load that record locally (using the convenient 1-record collection "Will Delete"), I don't see a references property at all.

So I thought maybe this was a fixed problem, and we just needed to reindex that record.  But reindexing it in production does not fix the problem.

**Comment by jrgriffiniii** [comment] 2019-02-19 16:39
This does not advance a solution for this issue, but I too am struggling to import the references field within my local development environment.  It does not at all appear to be related to the Exhibit metadata display configuration.

**Comment by jrgriffiniii** [comment] 2019-02-19 17:08
Perhaps this unrelated, but  https://github.com/pulibrary/pomegranate/blob/master/app/values/manifest_metadata.rb#L4 assumes that ordered properties in the manifest ensure that the link to the Figgy JSON-LD is *always* first:

```
> Array.wrap(@manifest["see_also"])
=> [{"@id"=>"https://figgy.princeton.edu/catalog/a1c9e1f2-d66c-434d-8863-3fe4ad4b4541.jsonld","format"=>"application/ld+json"},{"@id"=>"https://bibdata.princeton.edu/bibliographic/1425104", "format"=>"text/xml"}]
> Array.wrap(@manifest["see_also"]).find { |v| v["format"] == "application/ld+json" }
=> {"@id"=>"https://figgy.princeton.edu/catalog/a1c9e1f2-d66c-434d-8863-3fe4ad4b4541.jsonld", "format"=>"application/ld+json"}
```

**Comment by jrgriffiniii** [comment] 2019-02-19 18:24
I'm still searching for the process, but somehow `electronic_access_1display` within the catalog (Orangelight) Document is what is being inserted for this field within the production environment.

**Comment by jrgriffiniii** [comment] 2019-02-19 18:36
After discussing this with @tpendragon, it was discovered that this field was originally imported into the JSON-LD expression for Figgy (which, in turn, imported them into the `references`).  This has since been deprecated, but these Solr Documents have been cached into the sidecar, explaining why the documents cannot be reindexed within the production environment.

I proposed that this just be addressed by implementing a Rake Task which empties sidecar fields for SolrDocuments when these cases are encountered.

**Comment by jrgriffiniii** [comment] 2019-02-20 15:46
The SolrDocumentSidecar data was successfully cleaned and the SolrDocuments reindexed for all affected item within the Treasures of the East Asian Library collection.  After querying the Solr index, I've found that exhibits with slugs for the following collections still needed items cleaned:
- neareast
- ga_treasures
- msstreasures
- cotsen
- slavic
- islamicmss
- marquand
- music
- ealtoc
- pudl0058
- scheide

The sidecars have been cleaned, and the document reindexing jobs have been enqueued.

**Comment by jrgriffiniii** [comment] 2019-02-20 23:09
Only six documents appear to still have this problematic metadata:
- https://dpul.princeton.edu/ga_treasures/catalog/k930bx11x
- https://dpul.princeton.edu/msstreasures/catalog/hh63sz535
- https://dpul.princeton.edu/msstreasures/catalog/0c483n734
- https://dpul.princeton.edu/msstreasures/catalog/qv33s099j
- https://dpul.princeton.edu/msstreasures/catalog/s7526g75v
- https://dpul.princeton.edu/msstreasures/catalog/ff3658534

**Comment by jrgriffiniii** [comment] 2019-02-21 14:49
These have been manually enqueued for reindexing (I am not certain why these were not indexed).

**Comment by jrgriffiniii** [comment] 2019-02-22 20:47
Inspecting the first case, an error occurs during the reindexing job.  It appears that the JSON-LD representation for the resource in Figgy bears the `references` property, while this is not found in the JSON-LD generated from MarcLiberation:

https://figgy.princeton.edu/catalog/7ad1e904-de92-4ec2-bc6e-2116559cf20c.jsonld
https://bibdata.princeton.edu/bibliographic/10147675/jsonld

Perhaps this is what introduces a problem when importing the metadata properties from Figgy into DPUL?

**Comment by jrgriffiniii** [comment] 2019-02-22 21:06
This successfully reindexed properly within my local development environment, but I did notice that creating a new resource on Figgy (within the staging environment) did not import the problematic `references`.  Perhaps refreshing the metadata on the affected Figgy resources will address this problem.

**Comment by jrgriffiniii** [comment] 2019-02-22 21:45
Refreshing the metadata in Figgy before reindexing resolved this issue.

**Comment by jrgriffiniii** [comment] 2019-05-14 18:33
This is still occurring (as found when pairing on https://github.com/pulibrary/pomegranate/issues/536 with @hackmastera)

**Comment by escowles** [comment] 2019-09-09 17:51
We think this is fixed, and reindexing should fix any records that still have this problem.

**Closed by escowles** 2019-09-09 17:51 UTC
Labels: enhancement
