### ISSUE TITLE
Titles & Cropped images reverted in production

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pomegranate#182] opened 2017-01-18 18:12 UTC

**Comment by tpendragon** [comment] 2017-01-19 17:46
Having a hard time reproducing this - @joycebcat can you leave a note here next time you see it, with some steps on what exactly you did to make it happen? Also, when it happens could you try pressing ctrl+shift+f5 and see if the same thing happens? I'm wondering now if this is a caching issue, either server-side or in the browser.

**Comment by joycebcat** [comment] 2018-04-10 19:04
This is happening again.  Both Brittany and I on different machines and using different browsers have changed images in the music collection.  We put a new image in for the site, and when we clicked save, that image was stored, but the masthead changed--it jumped to the first image from the object rather than the image further inside the object that had been selected.  It seems that the "save changes" button isn't related to a specific tab, but rather to both masthead and site images.  The problem is that the masthead image selected keeps reverted to the first image.

**Comment by hackmastera** [comment] 2019-01-11 01:58
From @joycebcat's description this sounds like the same bug that was causing https://github.com/pulibrary/pomegranate/issues/448, which was resolved in https://github.com/pulibrary/figgy/pull/2249.

I tried this on staging and it appeared to work.

@joycebcat could you or maybe Brittany try it and let me know whether it is resolved? You will likely need to re-set the image one last time, but then once you save it I believe it will persist when you load the form again.

**Comment by joycebcat** [comment] 2019-01-17 20:29
I played around the the unpublished Latin American ephemera collection (which was a temp measure needed for a class awhile back when LAE was frozen).  I didn't have any problems adding or changing masthead and thumbnail images, so this looks like it is sorted!  Thanks.

**Closed** 2019-01-17 22:58 UTC
Labels: bug, review
